# Generated by Django 2.0.2 on 2018-02-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Я ментор'), ('2', 'Я ученик'), ('3', 'У меня есть стартап, ищу сокомандника')], max_length=1)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
    ]
