# Generated by Django 2.0.2 on 2018-02-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', "I'm a mentor"), ('2', "I'm a mentee"), ('3', "I've a startup, looking for a collaborator"), ('4', "I'm looking for a team and a project to join")], max_length=1)),
                ('text', models.TextField(max_length=800)),
                ('was_processed', models.BooleanField(default=False)),
                ('text_filtered', models.TextField(max_length=600)),
            ],
        ),
    ]
